#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { isDeepStrictEqual } from "node:util";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const artifactPath = resolve(
  repoRoot,
  "contracts/artifacts/contracts/StreamPayment.sol/StreamPayment.json",
);
const frontendAbiPath = resolve(
  repoRoot,
  "requestor-web/public/abi/StreamPayment.json",
);
const erc20AbiPath = resolve(repoRoot, "requestor-web/public/abi/ERC20.json");
const pythonAbiPath = resolve(
  repoRoot,
  "streaming-abi/golem_streaming_abi/__init__.py",
);

const checkOnly = process.argv.includes("--check");

if (!existsSync(artifactPath)) {
  execFileSync("npm", ["--prefix", "contracts", "run", "build"], {
    cwd: repoRoot,
    stdio: "inherit",
  });
}

const artifact = readJson(artifactPath);
const streamAbi = artifact.abi;
if (!Array.isArray(streamAbi)) {
  throw new Error(`Compiled StreamPayment artifact has no ABI: ${artifactPath}`);
}

const erc20Abi = readJson(erc20AbiPath).abi;
if (!Array.isArray(erc20Abi)) {
  throw new Error(`ERC20 ABI file has no ABI: ${erc20AbiPath}`);
}

assertRequiredEntries(streamAbi);

const frontendText = `${JSON.stringify({ abi: streamAbi }, null, 2)}\n`;
const pythonText = renderPythonAbi(streamAbi, erc20Abi);

if (checkOnly) {
  assertSameJson(frontendAbiPath, { abi: streamAbi });
  assertSameText(pythonAbiPath, pythonText);
  process.stdout.write("StreamPayment ABI files match the compiled artifact.\n");
} else {
  writeFileSync(frontendAbiPath, frontendText);
  writeFileSync(pythonAbiPath, pythonText);
  process.stdout.write("StreamPayment ABI files synchronized.\n");
}

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function assertSameJson(path, expected) {
  const actual = readJson(path);
  if (!isDeepStrictEqual(actual, expected)) {
    throw new Error(`${relative(path)} is not synchronized with StreamPayment artifact`);
  }
}

function assertSameText(path, expected) {
  const actual = readFileSync(path, "utf8");
  if (actual !== expected) {
    throw new Error(`${relative(path)} is not synchronized with StreamPayment artifact`);
  }
}

function assertRequiredEntries(abi) {
  const required = [
    "function:createStream",
    "function:glmToken",
    "function:nextStreamId",
    "function:streams",
    "function:terminate",
    "function:topUp",
    "function:usedLeaseIds",
    "function:withdraw",
    "event:StreamCreated",
    "event:Terminated",
    "event:ToppedUp",
    "event:Withdraw",
  ];
  const present = new Set(abi.map((entry) => `${entry.type}:${entry.name || ""}`));
  const missing = required.filter((entry) => !present.has(entry));
  if (missing.length) {
    throw new Error(`Compiled StreamPayment ABI is missing: ${missing.join(", ")}`);
  }
}

function renderPythonAbi(streamAbi, erc20Abi) {
  return [
    "# Generated by scripts/sync_stream_payment_abi.mjs. Do not edit by hand.",
    `STREAM_PAYMENT_ABI = ${pythonLiteral(streamAbi)}`,
    "",
    `ERC20_ABI = ${pythonLiteral(erc20Abi)}`,
    "",
    '__all__ = ["ERC20_ABI", "STREAM_PAYMENT_ABI"]',
    "",
  ].join("\n");
}

function pythonLiteral(value, indent = 0) {
  const pad = " ".repeat(indent);
  const child = " ".repeat(indent + 4);
  if (Array.isArray(value)) {
    if (!value.length) return "[]";
    return `[\n${value
      .map((item) => `${child}${pythonLiteral(item, indent + 4)}`)
      .join(",\n")}\n${pad}]`;
  }
  if (value && typeof value === "object") {
    const entries = Object.entries(value);
    if (!entries.length) return "{}";
    return `{\n${entries
      .map(
        ([key, item]) =>
          `${child}${JSON.stringify(key)}: ${pythonLiteral(item, indent + 4)}`,
      )
      .join(",\n")}\n${pad}}`;
  }
  if (typeof value === "boolean") return value ? "True" : "False";
  if (value === null) return "None";
  return JSON.stringify(value);
}

function relative(path) {
  return path.replace(`${repoRoot}/`, "");
}
