export const colors = {
  background: "var(--background)",
  surface: "var(--surface)",
  "surface-muted": "var(--surface-muted)",
  "surface-soft": "var(--surface-soft)",
  primary: "var(--primary)",
  "primary-hover": "var(--primary-hover)",
  "primary-soft": "var(--primary-soft)",
  success: "var(--success)",
  "success-soft": "var(--success-soft)",
  warning: "var(--warning)",
  "warning-soft": "var(--warning-soft)",
  danger: "var(--danger)",
  "danger-soft": "var(--danger-soft)",
  border: "var(--border)",
  "border-strong": "var(--border-strong)",
  "text-primary": "var(--text-primary)",
  "text-secondary": "var(--text-secondary)",
  "text-muted": "var(--text-muted)",
  "blue-text": "var(--blue-text)",
  brand: {
    50: "var(--primary-soft)",
    100: "#dfe7ff",
    200: "#bdccff",
    300: "#8fa8ff",
    400: "#5f7cff",
    500: "#315cff",
    600: "var(--primary)",
    700: "var(--primary-hover)",
    800: "#002bb8",
    900: "#001f85",
  },
};
