name: Publish Port Checker Package
on:
  push:
    branches:
      - main
    paths:
      - 'port-checker-server/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Configure Poetry
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Bump package version
        run: |
          python scripts/bump_versions.py port-checker-server/pyproject.toml
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - name: Build and publish
        working-directory: ./port-checker-server
        run: |
          poetry build
          poetry publish
